-- enUS Localization.
local _, Addon = ...
Addon:AddLocale("enUS",
{
TITAN_BUTTON_LABEL = "Vendor: ",
TITAN_MENU_TEXT = "Vendor",
TITAN_TOOLTIP_TITLE = "Vendor",
TITAN_TOOLTIP_TOSELL = "To Sell",
TITAN_TOOLTIP_TODELETE = "To Destroy",
TITAN_TOOLTIP_VALUE = "Value",
TITAN_MENU_NEW_RULE = "New Rule",
TITAN_MENU_SETTINGS = "Settings",
TITAN_MENU_KEYBINDINGS = "Keybindings",
TITAN_MENU_SHOWVALUETEXT = "Show Value Text",
TITAN_MENU_HIDE = "Hide",
TITAN_MENU_CHANGE_PROFILES = "Set Profile",
TITAN_MENU_PROFILES = "Profiles",
TITAN_MENU_RUNDESTROY = "Run Destroy",

}) -- END OF LOCALIZATION TABLE


